- name: install pip
  apt:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker

- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.gitlab.com
    username: amedia
    password: Maham2003
    reauthorize: yes

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
